# Project: Crystal Serpent Engine
# Makefile created by Red Panda C++ 2.23

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
RES      = Crystal_Serpent_Engine_private.res
OBJ      = CSE/application.o main.o CSE/window.o CSE/logger.o $(RES)
LINKOBJ  = CSE/application.o main.o CSE/window.o CSE/logger.o Crystal_Serpent_Engine_private.res
CLEANOBJ  =  CSE\application.o main.o CSE\window.o CSE\logger.o  Crystal_Serpent_Engine_private.res "Crystal Serpent Engine.exe"
LIBS     =  -L"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/lib" -L"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/x86_64-w64-mingw32/lib" -L"C:/Dev-Cpp/SDL/lib" -L"C:/Dev-Cpp/SDL/lib" -static-libgcc -lmingw32 -lSDL2main -lSDL2 -lSDL2_image -lSDL2_mixer
INCS     =  -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/include" -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/x86_64-w64-mingw32/include" -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/lib/gcc/x86_64-w64-mingw32/10.3.0/include" -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/lib/gcc/x86_64-w64-mingw32/10.3.0/include-fixed" -I"C:/Dev-Cpp/SDL/include/SDL2"  -I"C:/Dev-Cpp/SDL/include/SDL2" -I"C:/Temp/RedPanda-CPP/projects/Crystal Serpent Engine"
CXXINCS  =  -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/include" -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/x86_64-w64-mingw32/include" -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/lib/gcc/x86_64-w64-mingw32/10.3.0/include" -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/lib/gcc/x86_64-w64-mingw32/10.3.0/include/c++" -I"C:/Embarcadero DevCpp6.3_TDM-GCC9.2/TDM-GCC-64-10.3.0/lib/gcc/x86_64-w64-mingw32/10.3.0/include-fixed" -I"C:/Dev-Cpp/SDL/include/SDL2"  -I"C:/Dev-Cpp/SDL/include/SDL2" -I"C:/Temp/RedPanda-CPP/projects/Crystal Serpent Engine"
BIN      = "Crystal Serpent Engine.exe"
CXXFLAGS = $(CXXINCS)  -w -std=c++17
CFLAGS   = $(INCS)  -std=c17 -w
RM       = del /q /f
WINDRESFLAGS  = 

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	-$(RM) $(CLEANOBJ) > NUL 2>&1

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

CSE/application.o: CSE/application.cpp CSE/application.h CSE/core.h CSE/utils/utils.h CSE/common.h CSE/logger.h CSE/window.h CSE/protocore.h
	$(CPP) -c CSE/application.cpp -o CSE/application.o $(CXXFLAGS) 

main.o: main.cpp CSE/application.h CSE/core.h CSE/utils/utils.h CSE/common.h CSE/logger.h cse.h CSE/window.h CSE/protocore.h
	$(CPP) -c main.cpp -o main.o $(CXXFLAGS) 

CSE/window.o: CSE/window.cpp CSE/core.h CSE/utils/utils.h CSE/common.h CSE/logger.h CSE/window.h CSE/protocore.h
	$(CPP) -c CSE/window.cpp -o CSE/window.o $(CXXFLAGS) 

CSE/logger.o: CSE/logger.cpp CSE/logger.h
	$(CPP) -c CSE/logger.cpp -o CSE/logger.o $(CXXFLAGS) 

Crystal_Serpent_Engine_private.res: Crystal_Serpent_Engine_private.rc 
	$(WINDRES) -i Crystal_Serpent_Engine_private.rc --input-format=rc -o Crystal_Serpent_Engine_private.res -O coff $(WINDRESFLAGS) 

